info:
  component: API Proxy

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    users:
      path: /user/**
      service-id: user-microservice
      stripPrefix: false
server:
  port: 8765


eureka:
  instance:
    hostname: apiproxy
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761}/eureka/
