# management:
#   context-path: /admin
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    # leaseRenewalIntervalInSeconds: 10
    # statusPageUrlPath: /admin/info
    # healthCheckUrlPath: /admin/health
    hostname: configserver
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/


spring:
  cloud:
    config:
      server:
        git:
          uri: http://git.qiyestore.com/qiyestore/cloud-config-repo.git
          username: robot
          password: -1xEdto{k37X0fMbY?19zzoo|!{h9yb3
